/**
 * @file automation.controller.ts
 * @description Automation REST Endpoints — Sprint 5, Automation Team
 *
 * Exposes endpoints for running manual workflow executions and fetching
 * AI workflow recommendations generated by Gemini.
 */

import { Controller, Get, Post, Param, Body, Query, UseGuards, Request } from '@nestjs/common';
import { ApiTags, ApiBearerAuth, ApiOperation, ApiResponse, ApiParam } from '@nestjs/swagger';
import { JwtAuthGuard } from '../auth/guards/jwt-auth.guard';
import { AiService } from '../ai/ai.service';
import { WorkflowExecutorService } from './workflow-executor.service';

@ApiTags('Automation')
@ApiBearerAuth('JWT')
@UseGuards(JwtAuthGuard)
@Controller('automation')
export class AutomationController {
  constructor(
    private readonly aiService: AiService,
    private readonly workflowExecutor: WorkflowExecutorService,
  ) {}

  @Get('suggestions')
  @ApiOperation({ summary: 'Get AI-recommended automation workflows based on sales context' })
  @ApiResponse({ status: 200, description: 'List of AI recommendations successfully generated.' })
  async getSuggestions(@Query('context') context?: string) {
    return this.aiService.suggestWorkflows(context);
  }

  @Post('workflows/:id/execute')
  @ApiOperation({ summary: 'Manually run a workflow for a specific lead' })
  @ApiParam({ name: 'id', description: 'Workflow ID (cuid)' })
  @ApiResponse({ status: 201, description: 'Workflow execution launched successfully.' })
  async executeWorkflow(
    @Param('id') workflowId: string,
    @Body('leadId') leadId: string,
    @Body('context') runContext?: any,
  ) {
    return this.workflowExecutor.executeWorkflow(workflowId, leadId, runContext);
  }
}
